### ISSUE TITLE
a problem on the installation

### ISSUE THREAD

**Issue by helxsz** [tambetm/simple_dqn#1]
HI, I am using 14.04 ubuntu and I have followed the instruction until the step on this

``` javascript
ln -s /usr/lib/python2.7/dist-packages/cv2.so NEON_HOME/.venv/lib/python2.7/site-packages/
```

it shows me that

``` javascript
ln: target ‘NEON_HOME/.venv/lib/python2.7/site-packages/’ is not a directory: No such file or directory
```

I don't know NEON_HOME, what is definition of this, the path of the NEON project?

**Comment by tambetm** [comment]
By `NEON_HOME` I mean the folder where you installed (cloned) Neon. I'll clarify this in README.
