### ISSUE TITLE
should _restartRandom (src/agent.py) choose random action?

### ISSUE THREAD

**Issue by mw66** [tambetm/simple_dqn#11]
30:      reward = self.env.act(0)

right now all the action is fixed to 1st action

how about random.randint(0, self.num_actions)?

**Comment by mw66** [comment]
oh:

random.randint(0, self.num_actions-1)

**Comment by tambetm** [comment]
DeepMind uses null action in their code and evaluations, so I would stick with this. Other option is "human starts", which was introduced in [Gorila paper](http://www0.cs.ucl.ac.uk/staff/D.Silver/web/Applications_files/gorila.pdf). You are welcome to submit pull request for this.
