### ISSUE TITLE
src/nvis/figure.py upgrade to 0.11.1?

### ISSUE THREAD

**Issue by mw66** [tambetm/simple_dqn#12]
with 0.9.0

I have:

"src/nvis/figure.py", line 48, in deconv_figs
    x_range = Range1d(start=0, end=img_w)
NameError: global name 'Range1d' is not defined

after I 'pip install --upgrade bokeh', it works,

But the generated html gives browser:

"Uncaught TypeError: Bokeh.embed.embed_items is not a function"

update to 

http://cdn.pydata.org/bokeh/release/bokeh-0.11.1.min.js
http://cdn.pydata.org/bokeh/release/bokeh-0.11.1.min.css

solved the issue.

**Comment by tambetm** [comment]
Thanks, I just updated to Neon's latest deconv code and it seemed to work well. I didn't experience the problems you mention.
