### ISSUE TITLE
resume training will erase old results/game.csv & overwrite snapshots/game_$(EPOCH).pkl from 1

### ISSUE THREAD

**Issue by mw66** [tambetm/simple_dqn#13]
resume training will erase results/game.csv & overwrite snapshots/game_$(EPOCH).pkl from 1

I'd rather see append to game.csv, and snapshots file continuing from where it's left off.

**Comment by tambetm** [comment]
Yes, this is unfortunate feature. I would add something like --start_epoch command line argument and resume.sh script to deduce that from snapshot file name. I'm hoping to fix it soon, but maybe not in this week.
