### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by ShawnWongMILab** [tambetm/simple_dqn#14]
Traceback (most recent call last):
  File "src/main.py", line 102, in <module>
    mem = ReplayMemory(args.replay_size, args)
  File "/home/shawn/simple_dqn/src/replay_memory.py", line 12, in **init**
    self.screens = np.empty((self.size, args.screen_height, args.screen_width), dtype = np.uint8)
MemoryError

What is wrong with this? can anyone help me?

**Comment by tambetm** [comment]
Probably you don't have enough RAM. Try adding --replay_size 100000 to command line.

**Comment by ShawnWongMILab** [comment]
Awesome! Thanks a milllllllllion! It does works

**Comment by ShawnWongMILab** [comment]
Awesome! Thanks a milllllllllion!!! It does works!

**Comment by tambetm** [comment]
You are welcome. Probably the results with smaller replay memory are not that good, so you might want to find the highest value that works on your computer.
