### ISSUE TITLE
Visual and Test not work ?

### ISSUE THREAD

**Issue by mingtop** [tambetm/simple_dqn#15]
Two problems I got when I following you PostII . I am not sure where the problem is. Sincerely Thank you for answer~ ！

When I run the python virtual environment , I got a problem of h5py version is 1.83, I set the bashrc fixed the problem. 

./play.sh snape/breakout_77.pkl  work well. 

But when I test or visual kernel I got the following problems, here the debug infor.  
But when I test and visual the kernels of  snapshot, I got a problem with this:
1. ~/git/simple_dqn$ ./play.sh snapshots/breakout_77.pkl 
   Warning! **_HDF5 library version mismatched error**_
   The HDF5 header files used to compile this application do not match
   the version used by the HDF5 library to which this application is linked.
   Data corruption or segmentation faults may occur if the application continues.
   This can happen when an application was compiled by one version of HDF5 but
   linked with a different version of static or shared HDF5 library.
   You should recompile the application or check your shared library related
   settings such as 'LD_LIBRARY_PATH'.
   'HDF5_DISABLE_VERSION_CHECK' environment variable is set to 1, application will
   continue at your own risk.
   Headers are 1.8.11, library is 1.8.13
       SUMMARY OF THE HDF5 CONFIGURATION
       =================================
## General Information:

```
       HDF5 Version: 1.8.13
      Configured on: Wed Sep 10 18:56:58 CDT 2014
      Configured by: ilan@centos5x64.corp.continuum.io
     Configure mode: production
        Host system: x86_64-unknown-linux-gnu
      Uname information: Linux centos5x64.corp.continuum.io 2.6.18-348.el5 #1 SMP Tue Jan 8 17:53:53 EST 2013 x86_64 x86_64 x86_64 GNU/Linux
           Byte sex: little-endian
          Libraries: shared
     Installation point: /opt/anaconda1anaconda2anaconda3
```
## Compiling Options:

```
           Compilation Mode: production
                 C Compiler: /usr/bin/gcc44 ( gcc44 (GCC) 4.4.7 20120313 )
                     CFLAGS: 
                  H5_CFLAGS: -std=c99 -pedantic -Wall -Wextra -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline -Wno-long-long -Wfloat-equal -Wmissing-format-attribute -Wmissing-noreturn -Wpacked -Wdisabled-optimization -Wformat=2 -Wunreachable-code -Wendif-labels -Wdeclaration-after-statement -Wold-style-definition -Winvalid-pch -Wvariadic-macros -Wnonnull -Winit-self -Wmissing-include-dirs -Wswitch-default -Wswitch-enum -Wunused-macros -Wunsafe-loop-optimizations -Wc++-compat -Wstrict-overflow -Wlogical-op -Wlarger-than=2048 -Wvla -Wsync-nand -Wframe-larger-than=16384 -Wpacked-bitfield-compat -O3 -fomit-frame-pointer -finline-functions
                  AM_CFLAGS: 
                   CPPFLAGS: 
                H5_CPPFLAGS: -D_POSIX_C_SOURCE=199506L   -DNDEBUG -UH5_DEBUG_API
                AM_CPPFLAGS: -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_BSD_SOURCE 
           Shared C Library: yes
           Static C Library: no
```

  Statically Linked Executables: no
                        LDFLAGS: 
                     H5_LDFLAGS: 
                     AM_LDFLAGS: 
        Extra libraries:  -lpthread -lz -lrt -ldl -lm 
               Archiver: ar
             Ranlib: ranlib
          Debugged Packages: 
            API Tracing: no
## Languages:

```
                    Fortran: no

                        C++: no
```
## Features:

```
              Parallel HDF5: no
         High Level library: yes
               Threadsafety: yes
        Default API Mapping: v18
```

 With Deprecated Public Symbols: yes
         I/O filters (external): deflate(zlib)
         I/O filters (internal): shuffle,fletcher32,nbit,scaleoffset
                            MPE: no
                     Direct VFD: no
                        dmalloc: no
Clear file buffers before write: yes
           Using memory checker: no
         Function Stack Tracing: no
      Strict File Format Checks: no
   Optimization Instrumentation: no
       Large File Support (LFS): yes
A.L.E: Arcade Learning Environment (version 0.5.1)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./ale.cfg
Game console created:
  ROM file:  roms/breakout.bin
  Cart Name: Breakout - Breakaway IV (1978) (Atari)
  Cart MD5:  f34f08e5eb96e500e851a80be3277a56
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Screen Display Active. [Manual Control Mode] 'm' [Slowdown] 'a' [Speedup] 's' [VolumeDown] '[' [VolumeUp] ']'.
Running ROM file...
Random seed is 0
2016-05-15 22:35:08,283 Using minimal action set with size 4
2016-05-15 22:35:08,284 Using ALE Environment
2016-05-15 22:35:08,284 Replay memory size: 1000000
2016-05-15 22:35:08,606 Initialized NervanaGPU
2016-05-15 22:35:08,606 Backend: gpu, RNG seed: None
2016-05-15 22:35:08,754 Loading weights from snapshots/breakout_77.pkl
2016-05-15 22:35:09,983 Using old model serialization format. Serialized the model into new format
2016-05-15 22:35:09,988 Model weights loaded from snapshots/breakout_77.pkl
2016-05-15 22:35:09,988 Playing for 1 game(s)
2016-05-15 22:35:49,096   num_games: 1, average_reward: 302.000000, min_game_reward: 302, max_game_reward: 302
2016-05-15 22:35:49,096   last_exploration_rate: 0.050000, epoch_time: 21s, steps_per_second: 102
(.venv)jamin@jamin-lab:~/git/simple_dqn$ ./test.sh snapshots/pong_200.pk
Warning! **_HDF5 library version mismatched error**_
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
'HDF5_DISABLE_VERSION_CHECK' environment variable is set to 1, application will
continue at your own risk.
Headers are 1.8.11, library is 1.8.13
        SUMMARY OF THE HDF5 CONFIGURATION
        =================================
## General Information:

```
       HDF5 Version: 1.8.13
      Configured on: Wed Sep 10 18:56:58 CDT 2014
      Configured by: ilan@centos5x64.corp.continuum.io
     Configure mode: production
        Host system: x86_64-unknown-linux-gnu
      Uname information: Linux centos5x64.corp.continuum.io 2.6.18-348.el5 #1 SMP Tue Jan 8 17:53:53 EST 2013 x86_64 x86_64 x86_64 GNU/Linux
           Byte sex: little-endian
          Libraries: shared
     Installation point: /opt/anaconda1anaconda2anaconda3
```
## Compiling Options:

```
           Compilation Mode: production
                 C Compiler: /usr/bin/gcc44 ( gcc44 (GCC) 4.4.7 20120313 )
                     CFLAGS: 
                  H5_CFLAGS: -std=c99 -pedantic -Wall -Wextra -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline -Wno-long-long -Wfloat-equal -Wmissing-format-attribute -Wmissing-noreturn -Wpacked -Wdisabled-optimization -Wformat=2 -Wunreachable-code -Wendif-labels -Wdeclaration-after-statement -Wold-style-definition -Winvalid-pch -Wvariadic-macros -Wnonnull -Winit-self -Wmissing-include-dirs -Wswitch-default -Wswitch-enum -Wunused-macros -Wunsafe-loop-optimizations -Wc++-compat -Wstrict-overflow -Wlogical-op -Wlarger-than=2048 -Wvla -Wsync-nand -Wframe-larger-than=16384 -Wpacked-bitfield-compat -O3 -fomit-frame-pointer -finline-functions
                  AM_CFLAGS: 
                   CPPFLAGS: 
                H5_CPPFLAGS: -D_POSIX_C_SOURCE=199506L   -DNDEBUG -UH5_DEBUG_API
                AM_CPPFLAGS: -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_BSD_SOURCE 
           Shared C Library: yes
           Static C Library: no
```

  Statically Linked Executables: no
                        LDFLAGS: 
                     H5_LDFLAGS: 
                     AM_LDFLAGS: 
        Extra libraries:  -lpthread -lz -lrt -ldl -lm 
               Archiver: ar
             Ranlib: ranlib
          Debugged Packages: 
            API Tracing: no
## Languages:

```
                    Fortran: no

                        C++: no
```
## Features:

```
              Parallel HDF5: no
         High Level library: yes
               Threadsafety: yes
        Default API Mapping: v18
```

 With Deprecated Public Symbols: yes
         I/O filters (external): deflate(zlib)
         I/O filters (internal): shuffle,fletcher32,nbit,scaleoffset
                            MPE: no
                     Direct VFD: no
                        dmalloc: no
Clear file buffers before write: yes
           Using memory checker: no
         Function Stack Tracing: no
      Strict File Format Checks: no
   Optimization Instrumentation: no
       Large File Support (LFS): yes
A.L.E: Arcade Learning Environment (version 0.5.1)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./ale.cfg
Game console created:
  ROM file:  roms/pong.bin
  Cart Name: Video Olympics (1978) (Atari)
  Cart MD5:  60e0ea3cbe0913d39803477945e9e5ec
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Running ROM file...
Random seed is 0
2016-05-15 22:38:19,319 Using minimal action set with size 6
2016-05-15 22:38:19,319 Using ALE Environment
2016-05-15 22:38:19,319 Replay memory size: 1000000
2016-05-15 22:38:19,626 Initialized NervanaGPU
2016-05-15 22:38:19,627 Backend: gpu, RNG seed: None
2016-05-15 22:38:19,766 Loading weights from snapshots/pong_200.pk
Traceback (most recent call last):
  File "src/main.py", line 109, in <module>
    net.load_weights(args.load_weights)
  File "/home/jamin/git/simple_dqn/src/deepqnetwork.py", line 189, in load_weights
    self.model.load_params(load_path)
  File "/home/jamin/git/neon/neon/models/model.py", line 320, in load_params
    self.deserialize(load_obj(param_path), load_states=load_states)
  File "/home/jamin/git/neon/neon/util/persist.py", line 87, in load_obj
    load_path = open(load_path)
IOError: [Errno 2] No such file or directory: 'snapshots/pong_200.pk'

---
## 2.  visual  also got some problems 

2016-05-15 22:27:03,337 Using minimal action set with size 4
2016-05-15 22:27:03,338 Using ALE Environment
2016-05-15 22:27:03,338 Replay memory size: 1000000
2016-05-15 22:27:03,646 Initialized NervanaGPU
2016-05-15 22:27:03,646 Backend: gpu, RNG seed: None
2016-05-15 22:27:03,784 Loading weights from snapshots/breakout_200.pkl
2016-05-15 22:27:04,981 Using old model serialization format. Serialized the model into new format
2016-05-15 22:27:04,985 Model weights loaded from snapshots/breakout_200.pkl
2016-05-15 22:27:04,986 Playing for 1 game(s)
2016-05-15 22:27:13,828   num_games: 1, average_reward: 399.000000, min_game_reward: 399, max_game_reward: 399
2016-05-15 22:27:13,828   last_exploration_rate: 0.050000, epoch_time: 8s, steps_per_second: 201
2016-05-15 22:27:13,829 Collected 0 game states
Traceback (most recent call last):
  File "src/main.py", line 124, in <module>
    visualize(net.model, states, args.visualization_filters, args.visualization_file)
  File "/home/jamin/git/simple_dqn/src/visualization.py", line 9, in visualize
    data = data.reshape((data.shape[0], -1))
ValueError: total size of new array must be unchanged

**Comment by mingtop** [comment]
Hi, I trained "pong“ for 14 epoch, it gives a *.prm files in snapshot folder. 
It worked on ./test.sh snapshot/pong_14.prm.    But, it still can't visualization the kernels~~ 

Here is the error info:

Running ROM file...
Random seed is 0
2016-05-16 09:07:58,164 Using minimal action set with size 6
2016-05-16 09:07:58,164 Using ALE Environment
2016-05-16 09:07:58,164 Replay memory size: 1000000
2016-05-16 09:07:58,493 Initialized NervanaGPU
2016-05-16 09:07:58,493 Backend: gpu, RNG seed: None
2016-05-16 09:07:58,637 Loading weights from snapshots/pong_14.prm
2016-05-16 09:07:58,650 Model weights loaded from snapshots/pong_14.prm
2016-05-16 09:07:58,650 Playing for 1 game(s)
2016-05-16 09:08:09,779   num_games: 1, average_reward: -19.000000, min_game_reward: -19, max_game_reward: -19
2016-05-16 09:08:09,779   last_exploration_rate: 0.050000, epoch_time: 11s, steps_per_second: 165
2016-05-16 09:08:09,781 Collected 0 game states
Traceback (most recent call last):
  File "src/main.py", line 124, in <module>
    visualize(net.model, states, args.visualization_filters, args.visualization_file)
  File "/home/jamin/git/simple_dqn/src/visualization.py", line 9, in visualize
    data = data.reshape((data.shape[0], -1))
ValueError: total size of new array must be unchanged

Hoping you answer~

**Comment by tambetm** [comment]
Regarding the HDF5 library you are better asking somewhere else. I see you are using Anaconda, if this is binary distribution, then maybe the libraries it was compiled against do not match your runtime libraries.

Regarding visualization you are right, I haven't had time to update it against latest Neon. Feel free to submit a pull request! I'm keeping this issue open until the visualization is fixed.
