### ISSUE TITLE
ImportError: No module named cv2

### ISSUE THREAD

**Issue by fadedreams** [tambetm/simple_dqn#16]
Hi
I'v followed your instruction and after executing this command
./train.sh roms/breakout.bin
I ended up like this
///////////////////
(.venv) m@ubuntu:~/simple_dqn$ ./train.sh roms/breakout.bin
Traceback (most recent call last):
  File "src/main.py", line 4, in <module>
    from environment import ALEEnvironment, GymEnvironment
  File "/home/m/simple_dqn/src/environment.py", line 4, in <module>
    import cv2
ImportError: No module named cv2
////////////////////
I've searched /usr/lib/python2.7/dist-packages/ and I did not find a file named cv2.so
I only find a file named cv2.i386-linux-gnu.so
plz let me know what should I do? thanks

**Comment by tambetm** [comment]
You need to install Neon first, activate the virtual environment and make symlink for cv2.so in it. Refer to [README](https://github.com/tambetm/simple_dqn#simple-dqn-1) for instructions.

**Comment by fadedreams** [comment]
thanks for reply, in my case this worked
ln -s /usr/lib/python2.7/dist-packages/cv2.i386-linux-gnu.so  neon/.venv/lib/python2.7/site-packages/
but now another one arise
/////////////////////
(.venv) m@ubuntu:~/simple_dqn$ ./train.sh roms/breakout.bin
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
Traceback (most recent call last):
  File "src/main.py", line 4, in <module>
    from environment import ALEEnvironment, GymEnvironment
  File "/home/m/simple_dqn/src/environment.py", line 4, in <module>
    import cv2
ImportError: numpy.core.multiarray failed to import
//////////////////
Is this related to numpy version? Iam using  '1.11.0'

**Comment by tambetm** [comment]
Hmm, this might be nasty incompatibility between your system Python version and virtual env Python version. I never had this problem on Ubuntu.

Another option is to replace cv2 with PIL. cv2 is only used for resizing the image and converting it to grayscale. PIL can do it just as well and is easier to install to virtual environment. I would gladly accept pull request for this.

**Comment by fadedreams** [comment]
I'v tested simple_dqn on several Ubuntu versions
here is my result
ubuntu-14.04.4-desktop-amd64 LTS(working fine)
ubuntu-14.04.4-desktop-i386 (same above error)
ubuntu-16.04-desktop-amd64 LTS (same above error)
ubuntu-16.04-desktop-i386 (same above error)

**Comment by loofahcus** [comment]
Try to activate the virtual environment first, then:
pip install numpy --upgrade

This works for me~

**Comment by fadedreams** [comment]
Well done
