### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by fadedreams** [tambetm/simple_dqn#17]
I finally managed to run simple_dqn on ubuntu-14.04.4-desktop-amd64 LTS which is installed on virtualbox ,the host machine is Windows 7
I'v allocated 4GB to the VM and I got memory error what do i do ? thanks

(.venv)m@ubuntu:~/simple_dqn$ ./train.sh Breakout-v0 --environment gym
[2016-05-18 21:34:25,952] Making new env: Breakout-v0
[2016-05-18 21:34:25,988] Using Gym Environment
Traceback (most recent call last):
  File "src/main.py", line 102, in <module>
    mem = ReplayMemory(args.replay_size, args)
  File "/home/m/simple_dqn/src/replay_memory.py", line 12, in **init**
    self.screens = np.empty((self.size, args.screen_height, args.screen_width), dtype = np.uint8)
MemoryError
(.venv)m@ubuntu:~/simple_dqn$

**Comment by tambetm** [comment]
You need to decrease replay memory size. Default is 1000000, which takes about 6.5GB RAM. You could try if 500000 works in your case - use the command line option `--replay_size 500000`.

Also, if you are running the code in VirtualBox, then probably you are not using GPU? Then it's probably unbearably slow for training. Amazon EC2 is simple but costly solution, if you don't have access to GPU.
