### ISSUE TITLE
can the train process with CPU backend utilize multi-cores?

### ISSUE THREAD

**Issue by loofahcus** [tambetm/simple_dqn#18]
The neon example code like examples/mnist_mlp.py with CPU backend can take full advantage of multi-cores, but simple_dqn seems to use one core while running. Is it possible for simple_dqn to use all the cpu cores?

**Comment by tambetm** [comment]
I didn't find the documentation for multi-core, but I doubt it would be trivial to take advantage of this in simple_dqn. simple_dqn doesn't use the high level `fit()` method, but calls lower level `fprop()` and `bprop()` instead (to implement error clipping).

I you are going for CPU training, then it would be interesting to apply algorithms from [Asynchronous Methods for Deep Reinforcement Learning](https://arxiv.org/abs/1602.01783).

**Comment by loofahcus** [comment]
Thanks for your advice~
