### ISSUE TITLE
self.model.initialize(self.input_shape[:-1], self.cost)? correct dataset param?

### ISSUE THREAD

**Issue by mw66** [tambetm/simple_dqn#24]
from:
https://github.com/tambetm/simple_dqn/issues/22

https://github.com/tambetm/simple_dqn/blob/master/src/deepqnetwork.py#L49

how to change this then:

self.model.initialize(self.input_shape[:-1], self.cost)

I read the doc:

http://neon.nervanasys.com/docs/latest/_modules/neon/models/model.html#Model.initialize
def initialize(self, dataset, cost=None):

it suppose to get a dataset, is this a bug? should it be self.input[:-1] ?

If it's not a bug, will the code be more clear to change it to:

self.model.initialize(self.batch_size, self.cost)

since on
https://github.com/tambetm/simple_dqn/blob/master/src/deepqnetwork.py#L37
self.input_shape = (self.history_length,) + self.screen_dim + (self.batch_size,)

Same issue on line 67 too:
https://github.com/tambetm/simple_dqn/blob/master/src/deepqnetwork.py#L67
self.target_model = Model(layers = self._createLayers(num_actions))

**Comment by mw66** [comment]
oh, it should be:

https://github.com/tambetm/simple_dqn/blob/master/src/deepqnetwork.py#L71
      self.target_model.initialize(self.input_shape[:-1])

And I want to confirm that  self.cost is not need to be pass in.

**Comment by tambetm** [comment]
This model initialization was suggested by Nervana and at least it seems to work. I guess it accepts both dataset and shape as input, but to be sure you might want to check the Neon source.

`self.input_shape[:-1]` is the same as `(self.history_length,) + self.screen_dim`.
