### ISSUE TITLE
src/environment.py: (args.screen_width, args.screen_height) wrong order

### ISSUE THREAD

**Issue by mw66** [tambetm/simple_dqn#25]
else where you use:

self.dims = (args.screen_height, args.screen_width)

but in src/environment.py:

self.dims = (args.screen_width, args.screen_height)

**Comment by tambetm** [comment]
Yes, this might need clarification as well. In src/environment.py the self.dims is used only as an argument to cv2.resize(), which expects (width, height) order. Everywhere else it is used as dimensions of matrix, where height precedes width.

**Comment by mw66** [comment]
I noticed that self.dims only used in the call to cv2, in that case, how about remove these 2 class variables self.dims, and just directly code it in the cv2 call:

cv2.resize(screen, (args.screen_width, args.screen_height))

to avoid the confusion else where?
