### ISSUE TITLE
error when use openAI gym

### ISSUE THREAD

**Issue by nina124** [tambetm/simple_dqn#28]
It seems that OpenAI has changed its gym structure.
`pip install gym[atari]` can not be run. 
And when running `./train.sh Breakout-v0 --environment gym`, it returns error: No module named atari_py

Could you please change the code such that it is compatible with the current gym?

**Comment by longriyao** [comment]
I have the same problem. 
I run pip install "gym[atari]"  instead pip install gym[atari]
it was ok.

**Comment by nina124** [comment]
Thank you so much! It is solved now :)
