### ISSUE TITLE
error on no CUDA device is found while CUDA 7.0 is there

### ISSUE THREAD

**Issue by helxsz** [tambetm/simple_dqn#3]
This is the output when starting to train the model, it tells me that  Device 0 does not have CUDA compute capability 5.0 or greater, however I am running CUDA 7.0 with GTX750TI, I can run the Caffe model successfully. which part do I miss? 

``` javascript
 ./train.sh roms/pong.bin
A.L.E: Arcade Learning Environment (version 0.5.0)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./stellarc
Game console created:
  ROM file:  roms/pong.bin
  Cart Name: Video Olympics (1978) (Atari)
  Cart MD5:  60e0ea3cbe0913d39803477945e9e5ec
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Running ROM file...
Random Seed: Time
2015-10-09 06:23:24,651 Using full action set with size 18
2015-10-09 06:23:24,652 Replay memory size: 1000000
Traceback (most recent call last):
  File "src/main.py", line 85, in <module>
    net = DeepQNetwork(env.numActions(), args)
  File "/home/sizhexi/Desktop/dqn/simple_dqn/src/deepqnetwork.py", line 23, in __init__
    stochastic_round = args.stochastic_round)
  File "/home/sizhexi/Desktop/neon/neon/backends/__init__.py", line 90, in gen_backend
    "capability 5.0 or greater")
```

**Comment by tambetm** [comment]
I've had this problem once myself, but at the moment I wasn't able to replicate this. Anyway, make sure that:
- CUDA bin folder is in your PATH. To test that make sure `nvcc --version` works from command line.
- If you have several CUDA versions installed, make sure `nvcc --version` outputs the correct version number.
- Make sure CUDA libraries are in LD_LIBRARY_PATH or accessible by other means.

As a final resort run this code (replace NEON_HOME with location where you installed Neon):

```
python NEON_HOME/neon/backends/util/check_gpu.py
```

It should output the CUDA capability version and maybe this gives out some hints.

Let me know if you figure that out!

**Comment by helxsz** [comment]
by adding a line ' export PATH=/usr/local/cuda-7.5/bin:$PATH' to ~/.bashrc, and then 'source ~/.bashrc'.
Now when I typed the command in the terminal, nvcc -V, the terminal shows up 
      nvcc: NVIDIA (R) Cuda compiler driver 
      Cuda compilation toools, release 7.5, V7.5.17.

However, the RuntimeError:' Device 0 does not have CUDA compute capability 5.0 or greater 'still exists. and python backends/util/check_gpu.py show '0', which means no GPU is found

**Comment by tambetm** [comment]
What do you get when you change verbose=True on the last line of check_gpu.py? I vaguely remember, that I got "PyCUDA module not found". Basically I was missing pycuda package and it wasn't installed by Neon because I didn't have nvcc in PATH. I think if you run make again in Neon folder, it should be fixed. Let me know if this fixes your problem.

**Comment by helxsz** [comment]
When I changed the verbose=True, it is true I got 'PyCUDA module not found' when make. so I tried to install pip install pycuda, but then when make again, I just got the simple error message 'make: **\* [kernels] Error 1' . 

Ultimately I gave up on this neon project,  downloaded a new neon project, change 'verbose=True' and make again. (Note that I had already remove the pycuda in my system due to the error happened in previous neon project)  Here is the error I got below

``` javascript
 make
Traceback (most recent call last):
  File "neon/backends/make_kernels.py", line 23, in <module>
    from kernel_specs import get_cu_file, kernels, sass_dir, cu_dir, pre_dir, cubin_dir, dump_dir
  File "/home/sizhexi/Desktop/dqn/neon/neon/backends/kernel_specs.py", line 17, in <module>
    import pycuda.driver as drv
ImportError: No module named pycuda.driver
make: *** [kernels] Error 1
```

**Comment by tambetm** [comment]
I suspect, that still somehow pycuda is not getting installed. I took a look at Neon Makefile.

Here they check GPU by running `nvcc --version`:

```
# basic check to see if any CUDA compatible GPU is installed
# set this to false to turn off GPU related functionality
HAS_GPU := $(shell nvcc --version > /dev/null 2>&1 && echo true)
```

Here they check for GPU and install Python dependencies:

```
ifeq ($(HAS_GPU), true)
    @echo "Updating GPU dependencies in $(VIRTUALENV_DIR)..."
    @. $(ACTIVATE); pip install -r gpu_requirements.txt
    @echo
endif
```

You could try to install them manually by running `pip install -r gpu_requirements.txt` (with Neon virtualenv active of course).

**Comment by helxsz** [comment]
firstly, I went into the virtualenv active by 'source .venv/bin/activate.' and 'pip install -r gpu_requirements.txt'. at last, 'make' in the real and virtual situation, but still tells me 

```
import pycuda.driver as drv
```

ImportError: No module named pycuda.driver
make: **\* [kernels] Error 1
