### ISSUE TITLE
targets are not really copied when using cpu backend

### ISSUE THREAD

**Issue by loofahcus** [tambetm/simple_dqn#30]
[deepqnetwork.py#L133](https://github.com/tambetm/simple_dqn/blob/master/src/deepqnetwork.py#L133) should be:
`targets = preq.asnumpyarray().copy()`

Since for cpu backend, `asnumpyarray()` seems just get the reference of numpy array, which causes the modifications of `targets` impacting `preq`.

**Comment by tambetm** [comment]
Thanks @loofahcus! I was aware of this, but forgot to include the fix in this repo.
