### ISSUE TITLE
Error when training: "terminal state occurred during random initialization"

### ISSUE THREAD

**Issue by ferminquant** [tambetm/simple_dqn#37]
When I started training I got the error in the subject, so I changed the random_steps parameter to 1, and it started fine but failed after epoch 1. I commented the line that throws that error (agent.py line 36) and it is working fine now. 
I understand that this line checks if during training and in the random part, if it got a game over or a lost life, then it stops the execution with the stated error (environment.py line 111). But why does it do that? Why should it stop training if it lost a life during the first 30 (random_starts default value) steps in the random phase? Isn't the random phase prone to losing lives, since it is random?

**Comment by tambetm** [comment]
I've never seen it happen before, but I merged recently some changes that I didn't review too carefully, maybe they broke something. I'm not actively using this codebase, so it may take a while when I get a chance to review this. Feel free to send a PR!

**Comment by mthrok** [comment]
I think this is the result of https://github.com/tambetm/simple_dqn/pull/35, which I added.

Before that change, the code was not treating life loss as terminal state so terminal state did not happen during the random initialization. But now the life loss is treated as terminal state in training mode, it is possible to lose a life with in the first couple of frames.

I think we can just get rid of the assert statement.

**Comment by Jericho-Liao** [comment]
@mthrok @tambetm 
I have the same issue, Can you tell me  how to solve the issue, 
My quesetion is 

 I follow this URL: https://github.com/tambetm/simple_dqn#simple-dqn-1  install completion; when run command 
```
 ./train.sh roms/breakout.bin
A.L.E: Arcade Learning Environment (version 0.5.1)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./ale.cfg
Game console created:
  ROM file:  roms/breakout.bin
  Cart Name: Breakout - Breakaway IV (1978) (Atari)
  Cart MD5:  f34f08e5eb96e500e851a80be3277a56
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Running ROM file...
Random seed is 0
2017-01-19 12:02:31,570 Using minimal action set with size 4
2017-01-19 12:02:31,570 Using ALE Environment
2017-01-19 12:02:31,570 Replay memory size: 1000000
2017-01-19 12:02:31,808 Initialized NervanaGPU
2017-01-19 12:02:31,911 Backend: gpu, RNG seed: None
2017-01-19 12:02:31,961 Results are written to results/breakout.csv
2017-01-19 12:02:31,961 Populating replay memory with 50000 random moves
Traceback (most recent call last):
  File "src/main.py", line 136, in <module>
    agent.play_random(args.random_steps)
  File "/home/chenl/simple_dqn/src/agent.py", line 90, in play_random
    action, reward, screen, terminal = self.step(1)
  File "/home/chenl/simple_dqn/src/agent.py", line 78, in step
    self._restartRandom()
  File "/home/chenl/simple_dqn/src/agent.py", line 36, in _restartRandom
    assert not terminal, "terminal state occurred during random initialization"
AssertionError: terminal state occurred during random initialization
```

but i can run this command eg:` ./train.sh Breakout-v0 --environment gym`  .`/test.sh snapshots/breakout_77.pkl`; `./test_gym.sh snapshots/Breakout-v0_77.pkl`

how can i solution this issue ; Thank you!!

**Comment by Jericho-Liao** [comment]
注释掉这个文件agent.py的如下语句：
assert not terminal, "terminal state occurred during random initialization"

-----------------------

As stated in #37, the error stops occurring when commenting out the following line in the agent.py file:
assert not terminal, "terminal state occurred during random initialization"

**Comment by FrankBuss** [comment]
I had the same problem. Commenting the line out seems to work. Maybe should be changed in the repository.
