### ISSUE TITLE
simple_dqn code test problems

### ISSUE THREAD

**Issue by ctampier** [tambetm/simple_dqn#40]
Hi, I wanted to try simple_dqn so I followed all the installation instructions, but when I try to run
`./play.sh snapshots/breakout_77.pkl`
I get the following output to the terminal:

```
A.L.E: Arcade Learning Environment (version 0.5.1)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./ale.cfg
Game console created:
  ROM file:  roms/breakout.bin
  Cart Name: Breakout - Breakaway IV (1978) (Atari)
  Cart MD5:  f34f08e5eb96e500e851a80be3277a56
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Screen Display Active. [Manual Control Mode] 'm' [Slowdown] 'a' [Speedup] 's' [VolumeDown] '[' [VolumeUp] ']'.
Running ROM file...
Random seed is 0
2016-12-08 12:35:53,166 Using minimal action set with size 4
2016-12-08 12:35:53,167 Using ALE Environment
2016-12-08 12:35:53,167 Replay memory size: 1000000
Traceback (most recent call last):
  File "src/main.py", line 104, in <module>
    net = DeepQNetwork(env.numActions(), args)
  File "/home/carlos/Workspace/simple_dqn/src/deepqnetwork.py", line 34, in __init__
    stochastic_round = args.stochastic_round)
  File "/home/carlos/Workspace/neon/neon/backends/__init__.py", line 108, in gen_backend
    deterministic=deterministic)
  File "/home/carlos/Workspace/neon/neon/backends/backend.py", line 471, in allocate_backend
    raise ValueError("backend must be one of (%s)" % (names,))
ValueError: backend must be one of ('cpu')
```

I suppose that means it's not finding my GPU, because it does work with the `--backend cpu` option. I must add that I installed the CUDA 8.0 library after simple_dqn, neon and arcade learning environment. More specifically I followed the instructions in [the neon website](http://neon.nervanasys.com/index.html/installation.html). I also followed the [CUDA installation instructions ](http://docs.nvidia.com/cuda/cuda-installation-guide-linux/#axzz4SGHi3Z8N) to make sure I didn't miss anything. Finally I found [this issue](https://github.com/tambetm/simple_dqn/issues/3) where it's suggested to run the `check_gpu.py` util from the neon install. At first the output was "0", but then I ran `pip install pycuda` and after it was done the result was "5.2" (it found my GPU). Nevertheless my problem with simple_dqn not being able to run with GPU still exists.
I'm currently running Ubuntu 16.04 on an i7-4790k, GTX970 graphics card and 16GB RAM machine.

Any thoughts on what I could be missing?

**Comment by ctampier** [comment]
I have done a clean install on Ubuntu 14.04 and then installing first the CUDA 8.0 library and then neon, arcade learning environment and simple_dqn and the example is working properly. But the training is not, when I run:
`./train.sh roms/breakout.bin`
I get:
```
sh: 1: Syntax error: Missing '}'
A.L.E: Arcade Learning Environment (version 0.5.1)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./ale.cfg
Game console created:
  ROM file:  roms/breakout.bin
  Cart Name: Breakout - Breakaway IV (1978) (Atari)
  Cart MD5:  f34f08e5eb96e500e851a80be3277a56
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Running ROM file...
Random seed is 0
2016-12-08 23:32:30,001 Using minimal action set with size 4
2016-12-08 23:32:30,001 Using ALE Environment
2016-12-08 23:32:30,001 Replay memory size: 1000000
2016-12-08 23:32:30,216 Initialized NervanaGPU
2016-12-08 23:32:30,306 Backend: gpu, RNG seed: None
2016-12-08 23:32:30,347 Results are written to results/breakout.csv
2016-12-08 23:32:30,347 Populating replay memory with 50000 random moves
Traceback (most recent call last):
  File "src/main.py", line 136, in <module>
    agent.play_random(args.random_steps)
  File "/home/carlos/Workspace/simple_dqn/src/agent.py", line 90, in play_random
    action, reward, screen, terminal = self.step(1)
  File "/home/carlos/Workspace/simple_dqn/src/agent.py", line 78, in step
    self._restartRandom()
  File "/home/carlos/Workspace/simple_dqn/src/agent.py", line 36, in _restartRandom
    assert not terminal, "terminal state occurred during random initialization"
AssertionError: terminal state occurred during random initialization
```

**Comment by ctampier** [comment]
As stated in [#37](https://github.com/tambetm/simple_dqn/issues/37), the error stops occurring when commenting out the following line in the `agent.py` file:
`assert not terminal, "terminal state occurred during random initialization"`

**Comment by ctampier** [comment]
I'm not sure if this would be the best place to ask, but running the train.sh script saves the net weights after each epoc in files with .prm extension under the snapshots folder. Why isn't it in the same format as the example snapshots, which are in .pkl?

**Comment by tambetm** [comment]
You might be missing pycuda, see https://github.com/NervanaSystems/neon/issues/304.

Example snapshots were made with old version of Neon. If I remember correctly, .prm files are still pickled files, just the default extension has changed.

**Comment by riccitensor** [comment]
Exactly, I am having this in neon when running mnist_nlp example
```

(.venv2) gamer@gamer:~/neon$ python examples/mnist_mlp.py 
Traceback (most recent call last):
  File "examples/mnist_mlp.py", line 59, in <module>
    args = parser.parse_args()
  File "/home/gamer/neon/neon/util/argparser.py", line 366, in parse_args
    compat_mode=args.compat_mode)
  File "/home/gamer/neon/neon/backends/__init__.py", line 113, in gen_backend
    deterministic=deterministic)
  File "/home/gamer/neon/neon/backends/backend.py", line 471, in allocate_backend
    raise ValueError("backend must be one of (%s)" % (names,))
ValueError: backend must be one of ('cpu')

```

**Comment by tambetm** [comment]
Did you check NervanaSystems/neon#304 and it didn't solve your problem?

**Comment by ctampier** [comment]
It's been a while since I used this. I don't remember if this was exactly
the fix for that particular issue, but I do remember that in order to
properly make it work I had to start with a clean install of ubuntu, then
install the cuda toolkit <https://developer.nvidia.com/cuda-downloads>
(installation
guide here
<http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html>),
Neon, ALE and Simple DQN in that order.

If you want the step-by-step (most of this is in the Simple DQN README.md):

Install Cuda
a) Check hardware and SO compatibility
b) Download the cuda toolkit (Particularly for ubuntu 14.04:
https://developer.nvidia.com/compute/cuda/8.0/prod/local_installers/cuda-repo-ubuntu1404-8-0-local_8.0.44-1_amd64-deb
)
c) Execute the following commands to install the downloaded .deb file
    sudo dpkg -i cuda-repo-<distro>_<version>_<architecture>.deb
    sudo apt-get update
    sudo apt-get install cuda
d) Update environmental variables:
    export PATH="/usr/local/cuda/bin:"$PATH
    export
LD_LIBRARY_PATH="/usr/local/cuda/lib64:/usr/local/cuda/lib:/usr/local/lib:"$LD_LIBRARY_PATH

Install Neon
a) Install prerequisites:
    sudo apt-get install libhdf5-dev libyaml-dev libopencv-dev pkg-config
    sudo apt-get install python python-dev python-pip python-virtualenv
b) Clone repository:
    git clone https://github.com/NervanaSystems/neon.git
    cd neon
    make
c) Activate the virtual environment. From the Neon directory do:
    source .venv/bin/activate

Install ALE
a) Prerequisites:
    sudo apt-get install cmake libsdl1.2-dev
b) Clone in desired directory and compile:
    git clone https://github.com/mgbellemare/Arcade-Learning-Environment.git
    cd Arcade-Learning-Environment
    cmake -DUSE_SDL=ON -DUSE_RLGLUE=OFF -DBUILD_EXAMPLES=ON .
    make -j 4
c) Install python library (make sure to have the virtual environment
activated)
    pip install .

Install Simple DQN
a) Prerequisites:
    pip install numpy argparse logging
b) Install OpenCV and link library in virtual environment (NEON_HOME is the
directory where you cloned Neon)
    sudo apt-get install python-opencv
    ln -s /usr/lib/python2.7/dist-packages/cv2.so
NEON_HOME/.venv/lib/python2.7/site-packages/
c) Clone Simple DQN in desired directory
    git clone https://github.com/tambetm/simple_dqn
    cd simple_dqn

2017-10-25 12:12 GMT-03:00 Tambet Matiisen <notifications@github.com>:
