### ISSUE TITLE
error pi3 for  test_gym.py and main.py,

### ISSUE THREAD

**Issue by Robomate** [tambetm/simple_dqn#43]
hi, for pi3 raspian jessie:
 this time I tested test_gym.py and main.py,
I get a error that I am passing to few arguments:

the error happens for this line (the imports are all ok), but I have no idea which parameter is missing.
args = parser.parse_args()

usage: test_gym.py [-h] [--screen_width SCREEN_WIDTH]
                   [--screen_height SCREEN_HEIGHT] [--display DISPLAY]
                   [--replay_size REPLAY_SIZE]
                   [--history_length HISTORY_LENGTH]
                   [--learning_rate LEARNING_RATE]
                   [--discount_rate DISCOUNT_RATE] [--batch_size BATCH_SIZE]
                   [--optimizer {rmsprop,adam,adadelta}]
                   [--decay_rate DECAY_RATE] [--clip_error CLIP_ERROR]
                   [--target_steps TARGET_STEPS] [--min_reward MIN_REWARD]
                   [--max_reward MAX_REWARD] [--batch_norm BATCH_NORM]
                   [--backend {cpu,gpu}] [--device_id DEVICE_ID]
                   [--datatype {float16,float32,float64}]
                   [--stochastic_round [STOCHASTIC_ROUND]]
                   [--exploration_rate_start EXPLORATION_RATE_START]
                   [--exploration_rate_end EXPLORATION_RATE_END]
                   [--exploration_decay_steps EXPLORATION_DECAY_STEPS]
                   [--exploration_rate_test EXPLORATION_RATE_TEST]
                   [--train_frequency TRAIN_FREQUENCY]
                   [--train_repeat TRAIN_REPEAT]
                   [--random_starts RANDOM_STARTS]
                   [--random_steps RANDOM_STEPS] [--train_steps TRAIN_STEPS]
                   [--test_steps TEST_STEPS] [--epochs EPOCHS]
                   [--start_epoch START_EPOCH] [--load_weights LOAD_WEIGHTS]
                   [--save_weights_prefix SAVE_WEIGHTS_PREFIX]
                   [--num_episodes NUM_EPISODES] [--random_seed RANDOM_SEED]
                   env_id output_folder
test_gym.py: error: too few arguments

------------------
(program exited with code: 2)
Press return to continue

**Comment by tambetm** [comment]
I think you were supposed to run it like this:
```
./test_gym.sh snapshots/pong_141.pkl
```
