### ISSUE TITLE
Different absorbing states in ale and gym

### ISSUE THREAD

**Issue by carloderamo** [tambetm/simple_dqn#48]
Hi,
in the DeepMind paper on DQN they say that an episode ends when a life is lost. In the implementation of DQN, this is done in ale version of the environment counting the lives and checking, at training time, whether the number of lives changes. In the gym version of the environment the absorbing flag is the one returned by gym.step, however gym.step sets the absorbing flag to True only for game-over, not for every single life lost. This seems to be a bug. Am i correct?

**Comment by tambetm** [comment]
Yes, Gym environment is not updated to return game over on life loss. I'm not able to support this code any more, but you are welcome to submit pull request.
