### ISSUE TITLE
test with gym

### ISSUE THREAD

**Issue by mcbrs1a** [tambetm/simple_dqn#53]
Hi Im trying to test with gym, but not sure whether the snapshots provided in this code were trained with gym, from the example it states to run ./test_gym.sh snapshots/Breakout-v0_77.pkl which isn't present in the snapshots folder, running with breakout_77.pkl gives:

gym.error.Error: Attempted to look up malformed environment ID: breakout. (Currently all IDs must be of the form ^(?:[\w:-]+\/)?([\w:.-]+)-v(\d+)$.)

Are there any trained snapshots in this code based that were trained with gym so I can run an example?

How long would training take to produce a gyn snapshot running on a laptop with a cpu 4GB ram

Thanks

**Comment by tambetm** [comment]
It may very well be that there are no snapshots to be used with OpenAI Gym. I'm not using this codebase actively any more, there are now plenty of more modern implementations of DQN.

I would say training on laptop cpu with 4GB RAM is hopeless. Sorry, but those algorithms are really resource intensive.
