### ISSUE TITLE
Neon installation

### ISSUE THREAD

**Issue by jboilard1994** [tambetm/simple_dqn#57]
Neon needs to be installed in a Python virtual environment
Please specify installation steps to include this

**Comment by tambetm** [comment]
Unfortunately this repo is outdated and there are much better codebases out there. I would suggest to take a look at [this](https://github.com/keon/deep-q-learning) to learn the basics or [this](https://github.com/hill-a/stable-baselines) for full-blown DQN implementation for Atari.

**Comment by silkyrose** [comment]
Hi Tambetm,
I only have CPU no GPU, so can't move to keon.
Could you guide the below error?
    from core import colorful
ModuleNotFoundError: No module named 'core'

**Comment by silkyrose** [comment]
> Neon needs to be installed in a Python virtual environment
> Please specify installation steps to include this

Hi jboilard
I have installed neon 0.1.2, but still received many package include errors.
Do you know how to reslove the below problem:

C:\ProgramData\Anaconda3\python.exe E:/DPL/EdgeCloudResourcePool/DQN/deepqnetwork.py
Traceback (most recent call last):
  File "E:/DPL/EdgeCloudResourcePool/DQN/deepqnetwork.py", line 1, in <module>
    from neon.util.argparser import NeonArgparser
ModuleNotFoundError: No module named 'neon.util'
