### ISSUE TITLE
Segmentation fault on many games: STAMPEDE.BIN Barnstrm.bin Grandprx.bin Vanguard.bin ...

### ISSUE THREAD

**Issue by mw66** [tambetm/simple_dqn#7]
Hi,

I try to train some new game, but I got Segmentation fault, e.g.

$ ./train.sh roms/STAMPEDE.BIN 
A.L.E: Arcade Learning Environment (version 0.5.1)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./ale.cfg
Game console created:
  ROM file:  roms/STAMPEDE.BIN
  Cart Name: Stampede (1981) (Activision) [!]
  Cart MD5:  21d7334e406c2407e69dbddd7cec3583
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Running ROM file...
Random seed is 0
./train.sh: line 23:  7426 Segmentation fault      python src/main.py --save_weights_prefix $snapshots --csv_file $results $file $*

The games I tried so far:
STAMPEDE.BIN Barnstrm.bin Grandprx.bin Vanguard.bin ...
All give Segmentation fault.

How can I fix this?

Thanks!

**Comment by tambetm** [comment]
ALE tends to give segmentation fault when it doesn't support the game. Check this list for supported games:
https://github.com/mgbellemare/Arcade-Learning-Environment/tree/master/src/games/supported

None of the four games you mentioned is in the list.
